Repository SWM-KAWAI-MANS/party-run-infra, pull requests merged in 2023-08, with the labels that each got.

#4 matching service proxy buffer 해제
  dev/data/nginx/app.conf
Labels: 🐛 버그

#5 chore: battle 엔드포인트 수정
  dev/data/nginx/app.conf
Labels: ♻️ 리팩토링

#7 컨테이너 시스템 시간 변경
  dev/docker-compose.yml
Labels: ✨ 기능

#6 battle websocket 설정
  dev/data/nginx/app.conf
Labels: ✨ 기능

#8 배틀 웹소켓 접근 URL 변경
  dev/data/nginx/app.conf
Labels: ♻️ 리팩토링

#9 feat : mysql 설정
  dev/docker-compose.yml
Labels: ✨ 기능

#10 members location 추가
  dev/data/nginx/app.conf
Labels: ✨ 기능, 🏭인프라
